name: Build and Push Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: repository.bakapp.ir
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASS }}

      - name: Build Docker image
        run: |
          docker build -t repository.bakapp.ir/docker-hosted/my-image:latest .

      - name: Push Docker image
        run: |
          docker push repository.bakapp.ir/docker-hosted/my-image:latest
